# The following lines were added by compinstall {{{

zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' ignore-parents parent pwd directory
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' 'r:|[._-]=** r:|=**' 'l:|=* r:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' menu select
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle :compinstall filename '/home/drichardson42-gtri/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd extendedglob notify
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install }}}
# Use Neovim if it exists {{{
if type nvim > /dev/null 2>&1; then
    alias vim='nvim'
    alias vi='nvim'
    export EDITOR=nvim
elif type vim > /dev/null 2>&1; then
    export EDITOR=vim
else
    export EDITOR=vi
fi
# }}}
# Auto-correct Prompt {{{
setopt correct
autoload -U colors && colors
export SPROMPT="Correct $fg[red]%R$reset_color to $fg[green]%r$reset_color? (Yes, No, Abort, Edit) "
export SHELL=/bin/zsh
# }}}
# Key Bindings {{{
# Fix Delete and Home Keys in Prompt {{{
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line
bindkey "^[[3~" delete-char
bindkey "^[[Z"  menu-complete
# }}}
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward
# }}}
# Export Commands {{{
export LANG=en_US.UTF-8
export LC_ALL="en_US.UTF-8"
export PATH=$PATH:/usr/lib64/qt4/bin:$HOME/.local/bin:$HOME/bin/mview
export KEYTIMEOUT=10
# }}}
# Antigen Setup {{{
# Auto-install Antigen {{{
if [[ ! -d ~/.bundle ]]; then
    mkdir ~/.bundle
    curl -L git.io/antigen > ~/.bundle/antigen.zsh
fi
# }}}
source ~/.bundle/antigen.zsh
# Plugin Installation {{{
antigen bundle git
# CD to "frecent" directories with z
antigen bundle rupa/z
antigen bundle vi-mode
# bd = backwards cd
antigen bundle Tarrasch/zsh-bd
antigen bundle ael-code/zsh-colored-man-pages
antigen bundle zdharma/fast-syntax-highlighting
# Notify about aliases
antigen bundle MichaelAquilina/zsh-you-should-use
# Powerline prompt
antigen theme bhilburn/powerlevel9k

antigen apply
# }}}
# Plugin Settings {{{
# Powerline {{{
# DEFAULT_USER=drichardson42-gtri
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='153'
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='236'
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='153'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='153'
POWERLEVEL9K_DIR_HOME_BACKGROUND='153'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='153'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='236'
POWERLEVEL9K_DIR_HOME_FOREGROUND='236'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='236'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status vi_mode vcs)
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=" "
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
# }}}
# ZSH Syntax Highlighting {{{
FAST_HIGHLIGHT_STYLES[path]='bold'
FAST_HIGHLIGHT_STYLES[globbing]='fg=yellow'
FAST_HIGHLIGHT_STYLES[precommand]='fg=yellow,bold'
# }}}
# }}}
